/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package appbox;

/**
 *
 * @author victo
 */
public class Resultados extends javax.swing.JFrame {

    Pelea re = new Pelea();

    /**
     * Creates new form Resultados
     */
    public Resultados(Pelea pe) {
        initComponents();
        re = pe;
        this.setLocationRelativeTo(null);
        imprimirCalificaciones();
    }

    // Método para imprimir todas las calificaciones de cada juez
    public void imprimirCalificaciones() {
        StringBuilder sb = new StringBuilder();
        
        // Variables para llevar el conteo de cuántos jueces favorecieron a cada peleador
        int juecesPeleador1 = 0;
        int juecesPeleador2 = 0;

        for (int i = 0; i < re.ju.length; i++) {
            sb.append("=== Juez ").append(i + 1).append(" ===\n");

            // Variables para sumar los puntos de un solo juez
            int sumaJuezP1 = 0;
            int sumaJuezP2 = 0;

            // Recorremos y sumamos los puntos del Peleador 1
            sb.append("Peleador 1: ");
            for (Integer p : re.ju[i].puntos1) {
                sb.append(p).append(" ");
                sumaJuezP1 += p; // Sumamos al total del juez
            }
            sb.append(" | Total: ").append(sumaJuezP1).append("\n");

            // Recorremos y sumamos los puntos del Peleador 2
            sb.append("Peleador 2: ");
            for (Integer p : re.ju[i].puntos2) {
                sb.append(p).append(" ");
                sumaJuezP2 += p; // Sumamos al total del juez
            }
            sb.append(" | Total: ").append(sumaJuezP2).append("\n\n");

            // Determinamos a quién vio ganar este juez
            if (sumaJuezP1 > sumaJuezP2) {
                juecesPeleador1++;
            } else if (sumaJuezP2 > sumaJuezP1) {
                juecesPeleador2++;
            }
        }

        sb.append("---------------------------\n");
        sb.append("      RESULTADO FINAL      \n");
        sb.append("---------------------------\n");

        if (re.MotivoFin != null && !re.MotivoFin.trim().isEmpty() && !re.MotivoFin.equals("Motivo")) {
             sb.append("La pelea terminó antes de tiempo.\nMotivo: ").append(re.MotivoFin).append("\n\n");
        }

        // Declarar al ganador según las tarjetas de los jueces
        if (juecesPeleador1 > juecesPeleador2) {
            sb.append("¡GANADOR: Peleador 1 por decisión!\n");
        } else if (juecesPeleador2 > juecesPeleador1) {
            sb.append("¡GANADOR: Peleador 2 por decisión!\n");
        } else {
            sb.append("¡ES UN EMPATE!\n");
        }

        // Asignamos el texto final al JTextArea 
        if (txtAreaResultados != null) {
            txtAreaResultados.setText(sb.toString());
        } else {
            System.out.println(sb.toString()); 
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaResultados = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAreaResultados.setColumns(20);
        txtAreaResultados.setRows(5);
        jScrollPane1.setViewportView(txtAreaResultados);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaResultados;
    // End of variables declaration//GEN-END:variables
}
